### ISSUE TITLE
Table sample doesn't seem to work

### ISSUE THREAD

**Issue by inorton** [rprinz08/PyAgentX3#3]
When running the sample agent, the smptable example doesn't work:  Instead of the expected tabular data it prints:
```
Was that a table? SNMPv2-SMI::enterprises.8072.2.2.1
```

**Comment by inorton** [comment]
It seems, that instead of the snmptable line in the sample query script, this works instead:
```
snmptable -v 2c -c public -Ci localhost NET-SNMP-EXAMPLES-MIB::netSnmpIETFWGTable
```

**Comment by rprinz08** [comment]
thx for this report. Was unable to reproduce this behavior when querying the table directly (either with numerical OID or as name). Could be something with your installed MIBs. But added your statement using table name in addition to the query script.
