### ISSUE TITLE
Receive can miss multiple PDUs in buffer

### ISSUE THREAD

**Issue by weili-jiang** [rprinz08/PyAgentX3#7]
Thanks for continuing the work from the original. I've reviewed the delta and it looks like this fork is still susceptible to the issue fixed by this PR: https://github.com/hosthvo/pyagentx/pull/18

The code looks similar enough that I think the proposed patch would still largely apply. What do yo think?

**Comment by rprinz08** [comment]
You are right. It might be possible to miss a PDU. Should be fixed with commit 9e9f5fa0dc63462ac979e28d30f36afae3a719e7
