### ISSUE TITLE
BUG:  use Sized from collections deprecated in python 3.10  

### ISSUE THREAD

**Issue by marcocofano-lq** [rprinz08/PyAgentX3#8]
**Description**

Hi, 
From python 3.10 Sized like any other ABC seem to have been moved under collections.abc. It is used in the module pdu.py. 
There is also an alias in the typing module, which might be more convenient and explicit.

**Code**
In _pdu.py_
``` python
import struct
from ipaddress import IPv4Address, IPv6Address
from collections
import pprint
import pyagentx3
from pyagentx3.tools import hexdump
```

and used in line 78 of the same module:

``` python
def encode_octet(self, octet):
        data_len = 0
        data = octet

        if not isinstance(octet, collections.Sized):
            if isinstance(octet, IPv4Address) or isinstance(octet, IPv6Address):
                data = octet.packed
            else:
                data = str(octet)
```

should be changed to:

``` python
from collections.abc import Sized
```

and the code at line 78 should be changed accordingly. 

**Error message**

```
module 'collections' has no attribute 'Sized' 
```

hope it helps, thanks!

**Comment by rprinz08** [comment]
Was already fixed with commit ce6ed900191875e4f426497324aaca40e96a388b but updated PyPi package was missing. V1.4 PyPi package should now contain correct version.
